//! Deterministic CSS custom-property export for Meridian's WebKit UI.
//!
//! The editable values remain in `meridian-tokens` and `meridian-config`.
//! Web assets consume this generated contract and must not carry a second
//! hand-maintained palette, geometry scale or interaction recipe.

use std::fmt::Write;

use meridian_tokens::{
    contrast_text, Color, Elevation, Interaction, Launcher, Mask, Palette, Panel, Radius,
    Scrollbar, Typography,
};

use crate::{Decorations, Fonts, ThemeColors, ThemeSurface};

/// Increment only for a breaking custom-property rename or semantic change.
pub const CSS_TOKEN_SCHEMA_VERSION: u32 = 1;

/// Generate the shipped dark/light token sheet from the canonical palettes and
/// shared decoration defaults.
pub fn builtin_css_token_stylesheet() -> String {
    let dark = colors_from_palette(Palette::DARK);
    let light = colors_from_palette(Palette::LIGHT);
    css_token_stylesheet(&dark, &light, &Decorations::default(), &Fonts::default())
}

/// Generate a complete token sheet for the WebKit document.
///
/// Geometry, interaction and material values are emitted once in `:root`.
/// Theme selectors override only colour properties, preserving identical
/// layout and effects between light and dark mode.
pub fn css_token_stylesheet(
    dark: &ThemeColors,
    light: &ThemeColors,
    decorations: &Decorations,
    fonts: &Fonts,
) -> String {
    let mut css = String::new();
    writeln!(
        css,
        "/* Generated by meridian-config; schema v{CSS_TOKEN_SCHEMA_VERSION}. Do not edit. */"
    )
    .expect("writing to String cannot fail");
    writeln!(css, ":root {{").expect("writing to String cannot fail");
    write_shared_tokens(&mut css, decorations, fonts);
    write_color_tokens(&mut css, dark);
    writeln!(css, "  color-scheme: dark;").expect("writing to String cannot fail");
    writeln!(css, "}}").expect("writing to String cannot fail");
    writeln!(css).expect("writing to String cannot fail");
    writeln!(css, ":root[data-meridian-theme=\"light\"] {{")
        .expect("writing to String cannot fail");
    write_color_tokens(&mut css, light);
    writeln!(css, "  color-scheme: light;").expect("writing to String cannot fail");
    writeln!(css, "}}").expect("writing to String cannot fail");
    css
}

fn write_shared_tokens(css: &mut String, decorations: &Decorations, fonts: &Fonts) {
    let radius = Radius::DEFAULT;
    let interaction = Interaction::DEFAULT;
    let launcher = Launcher::DEFAULT;
    let panel = Panel::DEFAULT;
    let scrollbar = Scrollbar::DEFAULT;
    let mask = Mask::DEFAULT;
    let typography = Typography::DEFAULT;

    property(css, "schema-version", CSS_TOKEN_SCHEMA_VERSION);
    property(css, "font-ui", css_string(fonts.ui_family()));
    property_px(css, "type-caption-size", typography.caption_size);
    property_px(css, "type-body-size", typography.body_size);
    property_px(css, "type-title-size", typography.title_size);
    property_px(css, "type-display-size", typography.display_size);
    property(css, "type-regular-weight", typography.regular_weight);
    property(css, "type-medium-weight", typography.medium_weight);
    property(css, "type-strong-weight", typography.strong_weight);
    property_px(css, "launcher-width", launcher.width);
    property_px(css, "launcher-height", launcher.height);
    property_px(css, "launcher-app-icon-size", launcher.app_icon_size);
    property_px(css, "panel-height", panel.height);
    property_px(css, "panel-bottom-gap", panel.bottom_gap);
    property_px(css, "panel-side-margin", panel.side_margin);
    property_px(css, "panel-top-shadow", panel.top_shadow);
    property_px(css, "panel-control-height", panel.control_height);
    property_px(css, "panel-app-icon-size", panel.app_icon_size);
    property_px(css, "panel-control-width", panel.control_width);
    property_px(css, "panel-clock-width", panel.clock_width);
    property_px(css, "radius-none", radius.none);
    property_px(css, "radius-sm", radius.sm);
    property_px(css, "radius-md", radius.md);
    property_px(css, "radius-lg", radius.lg);
    property_px(css, "radius-xl", radius.xl);
    property_px(css, "decoration-border-width", decorations.border_width);
    property_px(css, "decoration-corner-radius", decorations.corner_radius);
    property_px(css, "layout-gap", decorations.gap);
    property(css, "shadow-enabled", flag(decorations.shadow));
    property_px(css, "shadow-radius", decorations.shadow_radius);
    property_px(css, "shadow-radius-top", decorations.shadow_radius_top);
    property_number(css, "shadow-alpha", decorations.shadow_alpha);
    property_px(css, "shadow-offset-y", decorations.shadow_offset_y);
    property(css, "glass-enabled", flag(decorations.glass));
    property(css, "glass-blur-enabled", flag(decorations.glass_blur));
    property_number(css, "glass-alpha", decorations.glass_alpha);
    property_number(css, "glass-specular", decorations.glass_specular);
    property_px(css, "glass-blur-radius", decorations.glass_blur_radius);
    property_number(css, "glass-frame-alpha", decorations.glass_frame_alpha);
    property_number(css, "glass-button-alpha", decorations.glass_button_alpha);
    property_number(css, "glass-divider-alpha", decorations.glass_divider_alpha);
    property_number(css, "interaction-hover-mix", interaction.hover_lighten);
    property_number(css, "interaction-pressed-mix", interaction.pressed_darken);
    property(css, "interaction-neutral-hover", interaction.neutral_hover);
    property(
        css,
        "interaction-neutral-pressed",
        interaction.neutral_pressed,
    );
    property_number(
        css,
        "interaction-accent-idle-alpha",
        alpha(interaction.accent_idle_alpha),
    );
    property_number(
        css,
        "interaction-accent-hover-alpha",
        alpha(interaction.accent_hover_alpha),
    );
    property_number(css, "selection-focused-mix", Interaction::SELECTION_FOCUSED);
    property_number(
        css,
        "selection-expanded-mix",
        Interaction::SELECTION_EXPANDED,
    );
    property_number(css, "selection-active-mix", Interaction::SELECTION_ACTIVE);
    property_number(
        css,
        "selection-selected-mix",
        Interaction::SELECTION_SELECTED,
    );
    property_number(css, "selection-hover-mix", Interaction::SELECTION_HOVER);
    property_number(css, "interaction-armed-mix", Interaction::ARMED_DARKEN);
    property_number(
        css,
        "interaction-selected-mix",
        Interaction::SELECTED_LIGHTEN,
    );
    write_surface(css, "panel", decorations, ThemeSurface::Panel);
    write_surface(css, "launcher", decorations, ThemeSurface::Launcher);
    write_surface(css, "popup", decorations, ThemeSurface::Popup);
    write_surface(css, "modal", decorations, ThemeSurface::Modal);
    write_surface(css, "control", decorations, ThemeSurface::Control);
    write_elevation(css, "panel", Elevation::PANEL);
    write_elevation(css, "popup", Elevation::POPUP);
    write_elevation(css, "launcher", Elevation::LAUNCHER);
    property(
        css,
        "color-launcher-shadow",
        with_alpha(Palette::TEXT_ON_LIGHT, Elevation::LAUNCHER.alpha),
    );
    property(
        css,
        "color-panel-shadow",
        with_alpha(Palette::TEXT_ON_LIGHT, Elevation::PANEL.alpha),
    );
    property_number(css, "launcher-band-alpha", alpha(launcher.band_alpha));
    property_number(css, "launcher-cell-alpha", alpha(launcher.cell_alpha));
    property_number(css, "launcher-hover-alpha", alpha(launcher.hover_alpha));
    property_number(
        css,
        "launcher-selected-alpha",
        alpha(launcher.selected_alpha),
    );
    property_number(
        css,
        "launcher-search-field-alpha",
        alpha(launcher.search_field_alpha),
    );
    property_number(
        css,
        "launcher-bento-accent-alpha",
        alpha(launcher.bento_accent_alpha),
    );
    property_number(
        css,
        "launcher-power-armed-alpha",
        alpha(launcher.power_armed_alpha),
    );
    property_number(css, "launcher-divider-alpha", alpha(launcher.divider_alpha));
    property_number(css, "panel-hover-alpha", alpha(panel.hover_alpha));
    property_number(css, "panel-active-alpha", alpha(panel.active_alpha));
    property_number(css, "panel-divider-alpha", alpha(panel.divider_alpha));
    property_number(css, "scrollbar-track-alpha", alpha(scrollbar.track_alpha));
    property_number(css, "scrollbar-thumb-alpha", alpha(scrollbar.thumb_alpha));
    property_number(css, "mask-dim-alpha", alpha(mask.dim_alpha));
}

fn write_surface(css: &mut String, name: &str, decorations: &Decorations, surface: ThemeSurface) {
    let treatment = decorations.surface_treatment(surface);
    property_px(css, &format!("surface-{name}-radius"), treatment.radius);
    property_number(css, &format!("surface-{name}-tint"), treatment.tint_amount);
    property_px(css, &format!("surface-{name}-blur"), treatment.blur_radius);
    property_number(
        css,
        &format!("surface-{name}-fill-alpha"),
        alpha(treatment.fill_alpha),
    );
    property_number(
        css,
        &format!("surface-{name}-frame-alpha"),
        alpha(treatment.frame_alpha),
    );
}

fn write_elevation(css: &mut String, name: &str, elevation: Elevation) {
    property_px(css, &format!("elevation-{name}-blur"), elevation.blur);
    property_number(css, &format!("elevation-{name}-alpha"), elevation.alpha);
    property_px(
        css,
        &format!("elevation-{name}-offset-y"),
        elevation.offset_y,
    );
    property_px(
        css,
        &format!("elevation-{name}-extent"),
        elevation.outer_extent(),
    );
}

fn write_color_tokens(css: &mut String, colors: &ThemeColors) {
    for (name, color) in [
        ("background", colors.background),
        ("surface", colors.surface),
        ("surface-alt", colors.surface_alt),
        ("accent", colors.accent),
        ("accent-alt", colors.accent_alt),
        ("text", colors.text),
        ("text-dim", colors.text_dim),
        ("border", colors.border),
        ("error", colors.error),
        ("warning", colors.warning),
        ("success", colors.success),
    ] {
        property(css, &format!("color-{name}"), color);
    }
    property(css, "color-on-accent", contrast_text(colors.accent));
    let launcher = Launcher::DEFAULT;
    let panel = Panel::DEFAULT;
    property(
        css,
        "color-launcher-hover",
        with_alpha(colors.surface_alt, alpha(launcher.hover_alpha)),
    );
    property(
        css,
        "color-launcher-selected",
        with_alpha(colors.accent, alpha(launcher.selected_alpha)),
    );
    property(
        css,
        "color-launcher-search",
        with_alpha(colors.surface_alt, alpha(launcher.search_field_alpha)),
    );
    property(
        css,
        "color-launcher-divider",
        with_alpha(colors.accent, alpha(launcher.divider_alpha)),
    );
    property(
        css,
        "color-panel-hover",
        with_alpha(colors.surface_alt, alpha(panel.hover_alpha)),
    );
    property(
        css,
        "color-panel-active",
        with_alpha(colors.accent, alpha(panel.active_alpha)),
    );
    property(
        css,
        "color-panel-divider",
        with_alpha(colors.text, alpha(panel.divider_alpha)),
    );
}

fn with_alpha(color: Color, value: f32) -> Color {
    Color::rgba(
        color.r,
        color.g,
        color.b,
        (value.clamp(0.0, 1.0) * u8::MAX as f32).round() as u8,
    )
}

fn property(css: &mut String, name: &str, value: impl std::fmt::Display) {
    writeln!(css, "  --meridian-{name}: {value};").expect("writing to String cannot fail");
}

fn property_px(css: &mut String, name: &str, value: impl std::fmt::Display) {
    writeln!(css, "  --meridian-{name}: {value}px;").expect("writing to String cannot fail");
}

fn property_number(css: &mut String, name: &str, value: f32) {
    property(css, name, decimal(value));
}

fn decimal(value: f32) -> String {
    let formatted = format!("{value:.6}");
    formatted
        .trim_end_matches('0')
        .trim_end_matches('.')
        .to_string()
}

fn alpha(value: u8) -> f32 {
    value as f32 / u8::MAX as f32
}

fn flag(value: bool) -> u8 {
    u8::from(value)
}

fn css_string(value: &str) -> String {
    let mut escaped = String::from("\"");
    for character in value.chars() {
        match character {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '<' => escaped.push_str("\\3c "),
            '>' => escaped.push_str("\\3e "),
            value if value.is_control() => escaped.push(' '),
            value => escaped.push(value),
        }
    }
    escaped.push('"');
    escaped
}

fn colors_from_palette(palette: Palette) -> ThemeColors {
    ThemeColors {
        background: palette.background,
        surface: palette.surface,
        surface_alt: palette.surface_alt,
        accent: palette.accent,
        accent_alt: palette.accent_alt,
        text: palette.text,
        text_dim: palette.text_dim,
        border: palette.border,
        error: palette.error,
        warning: palette.warning,
        success: palette.success,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builtin_export_matches_versioned_snapshot() {
        assert_eq!(
            builtin_css_token_stylesheet(),
            include_str!("../tests/fixtures/css_tokens_v1.css")
        );
    }

    #[test]
    fn light_selector_contains_colors_but_no_geometry() {
        let css = builtin_css_token_stylesheet();
        let light = css
            .split_once(":root[data-meridian-theme=\"light\"]")
            .expect("light selector")
            .1;
        assert!(light.contains("--meridian-color-background"));
        assert!(!light.contains("--meridian-radius-"));
        assert!(!light.contains("--meridian-glass-"));
        assert!(!light.contains("--meridian-elevation-"));
    }

    #[test]
    fn custom_colors_and_decorations_flow_into_css() {
        let mut dark = colors_from_palette(Palette::DARK);
        dark.accent = meridian_tokens::Color::rgb(1, 2, 3);
        let decorations = Decorations {
            corner_radius: 17,
            ..Decorations::default()
        };
        let css = css_token_stylesheet(
            &dark,
            &colors_from_palette(Palette::LIGHT),
            &decorations,
            &Fonts::default(),
        );
        assert!(css.contains("--meridian-color-accent: #010203;"));
        assert!(css.contains("--meridian-decoration-corner-radius: 17px;"));
    }

    #[test]
    fn font_family_is_quoted_and_cannot_close_the_style_element() {
        let fonts = Fonts {
            ui: "Bad </style> Font 11".to_string(),
        };
        let css = css_token_stylesheet(
            &colors_from_palette(Palette::DARK),
            &colors_from_palette(Palette::LIGHT),
            &Decorations::default(),
            &fonts,
        );
        assert!(!css.contains("</style>"));
        assert!(css.contains("Bad \\3c /style\\3e  Font"));
    }
}
