//! Export the active Meridian theme to the *legacy* desktop-config files that
//! GTK and KDE/Qt applications actually read — the piece the appearance portal
//! alone cannot cover.
//!
//! Meridian serves `org.freedesktop.appearance color-scheme` over the Settings
//! portal, and that works. But most toolkits do **not** reconstruct a palette
//! from the portal:
//!   - GTK apps read `~/.config/gtk-3.0/settings.ini` / `gtk-4.0/settings.ini`
//!     and the `org.gnome.desktop.interface color-scheme` gsetting.
//!   - KDE/Qt apps (Breeze / `KColorScheme`, e.g. Gwenview, Dolphin) build their
//!     palette from `~/.config/kdeglobals` — *not* from the portal. Without a
//!     dark `kdeglobals` they fall back to the hard-coded Breeze **light**
//!     palette, which is why a KDE app stays light even though the portal
//!     reports `color-scheme = 1` (prefer dark).
//!
//! `KColorScheme` reads `kdeglobals` only at application **startup**, so these
//! files must exist *before* an app launches. We therefore export at session
//! start (before autostart apps) and again on every live theme switch.
//!
//! Every value is derived from the active [`ThemeConfig`] — there is no
//! hard-coded colour here (the only literals are GTK/KDE *theme names* and the
//! `Breeze` widget style, which are identifiers, not design values).

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use meridian_config::{Color, ThemeConfig};

/// Write all legacy theme files derived from `theme` and best-effort sync the
/// GNOME gsettings keys. Never fails the caller; problems are logged.
pub(crate) fn export_theme(theme: &ThemeConfig) {
    let Some(dir) = config_home() else {
        tracing::warn!("theme_export: no config dir (XDG_CONFIG_HOME/HOME unset); skipping");
        return;
    };
    write_config_file(&dir.join("kdeglobals"), &kdeglobals_contents(theme));
    let gtk = gtk_settings_ini(theme);
    write_config_file(&dir.join("gtk-3.0").join("settings.ini"), &gtk);
    write_config_file(&dir.join("gtk-4.0").join("settings.ini"), &gtk);
    apply_gsettings(theme);
    tracing::info!(
        "theme_export: legacy theme files written (dark={})",
        !theme.appearance_is_light()
    );
}

/// `~/.config` resolved from `XDG_CONFIG_HOME` (must be absolute) or `HOME`.
fn config_home() -> Option<PathBuf> {
    if let Some(x) = std::env::var_os("XDG_CONFIG_HOME") {
        let p = PathBuf::from(x);
        if p.is_absolute() {
            return Some(p);
        }
    }
    std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".config"))
}

fn write_config_file(path: &Path, contents: &str) {
    if let Some(parent) = path.parent() {
        if let Err(e) = fs::create_dir_all(parent) {
            tracing::warn!("theme_export: mkdir {:?}: {}", parent, e);
            return;
        }
    }
    if let Err(e) = fs::write(path, contents) {
        tracing::warn!("theme_export: write {:?}: {}", path, e);
    }
}

/// `kdeglobals` colour scheme derived from the theme. KColorScheme reads the
/// `[Colors:*]` groups directly, so a matching `*.colors` file in
/// `/usr/share/color-schemes` is **not** required — the inline groups are
/// self-sufficient.
pub(crate) fn kdeglobals_contents(theme: &ThemeConfig) -> String {
    let c = &theme.colors;
    let scheme = if theme.appearance_is_light() {
        "MeridianLight"
    } else {
        "MeridianDark"
    };
    let sel_fg = readable_on(c.accent, theme);

    let mut s = String::new();
    s.push_str("# Generated by Meridian (theme_export). Managed file.\n\n");
    // Window chrome = surface; content/list/edit views = darkest background;
    // buttons/tooltips = surface_alt. This mirrors Breeze's Window>View depth.
    push_color_group(&mut s, "Colors:Window", c.surface, theme);
    push_color_group(&mut s, "Colors:View", c.background, theme);
    push_color_group(&mut s, "Colors:Button", c.surface_alt, theme);
    push_color_group(&mut s, "Colors:Tooltip", c.surface_alt, theme);
    push_color_group(&mut s, "Colors:Complementary", c.background, theme);

    // Selection uses the accent as a fill with a readable foreground.
    s.push_str("[Colors:Selection]\n");
    s.push_str(&format!("BackgroundNormal={}\n", triplet(c.accent)));
    s.push_str(&format!("ForegroundNormal={}\n", triplet(sel_fg)));
    s.push_str(&format!("ForegroundInactive={}\n", triplet(sel_fg)));
    s.push_str(&format!("DecorationFocus={}\n", triplet(c.accent)));
    s.push_str(&format!("DecorationHover={}\n", triplet(c.accent)));
    s.push('\n');

    s.push_str("[General]\n");
    s.push_str(&format!("ColorScheme={scheme}\n\n"));
    s.push_str("[Icons]\n");
    s.push_str(&format!("Theme={}\n\n", theme.icons.theme));
    s.push_str("[KDE]\n");
    s.push_str("widgetStyle=Breeze\n");
    s
}

/// One `[Colors:<group>]` block: background from `bg`, all foreground/decoration
/// roles from the theme palette.
fn push_color_group(out: &mut String, group: &str, bg: Color, theme: &ThemeConfig) {
    let c = &theme.colors;
    out.push_str(&format!("[{group}]\n"));
    out.push_str(&format!("BackgroundNormal={}\n", triplet(bg)));
    out.push_str(&format!("BackgroundAlternate={}\n", triplet(c.surface_alt)));
    out.push_str(&format!("ForegroundNormal={}\n", triplet(c.text)));
    out.push_str(&format!("ForegroundInactive={}\n", triplet(c.text_dim)));
    out.push_str(&format!("ForegroundActive={}\n", triplet(c.accent)));
    out.push_str(&format!("ForegroundLink={}\n", triplet(c.accent)));
    out.push_str(&format!("ForegroundVisited={}\n", triplet(c.accent_alt)));
    out.push_str(&format!("ForegroundNegative={}\n", triplet(c.error)));
    out.push_str(&format!("ForegroundNeutral={}\n", triplet(c.warning)));
    out.push_str(&format!("ForegroundPositive={}\n", triplet(c.success)));
    out.push_str(&format!("DecorationFocus={}\n", triplet(c.accent)));
    out.push_str(&format!("DecorationHover={}\n", triplet(c.accent)));
    out.push('\n');
}

/// `~/.config/gtk-{3,4}.0/settings.ini` content for GTK apps.
pub(crate) fn gtk_settings_ini(theme: &ThemeConfig) -> String {
    let dark = !theme.appearance_is_light();
    let prefer_dark = u8::from(dark);
    let gtk_theme = if dark { "Adwaita-dark" } else { "Adwaita" };
    format!(
        "[Settings]\n\
         gtk-application-prefer-dark-theme={prefer_dark}\n\
         gtk-theme-name={gtk_theme}\n\
         gtk-icon-theme-name={icons}\n\
         gtk-font-name={font}\n\
         gtk-cursor-theme-name={cursor}\n\
         gtk-cursor-theme-size={cursor_size}\n",
        icons = theme.icons.theme,
        font = theme.fonts.ui,
        cursor = theme.cursor.theme,
        cursor_size = theme.cursor.size,
    )
}

/// Best-effort sync of the GNOME interface gsettings (libadwaita / GTK4 honour
/// `color-scheme` at runtime). No-op if `gsettings` is absent.
fn apply_gsettings(theme: &ThemeConfig) {
    let dark = !theme.appearance_is_light();
    let scheme = if dark { "prefer-dark" } else { "default" };
    let gtk_theme = if dark { "Adwaita-dark" } else { "Adwaita" };
    set_gsetting("org.gnome.desktop.interface", "color-scheme", scheme);
    set_gsetting("org.gnome.desktop.interface", "gtk-theme", gtk_theme);
    set_gsetting("org.gnome.desktop.interface", "icon-theme", &theme.icons.theme);
}

fn set_gsetting(schema: &str, key: &str, value: &str) {
    if let Err(e) = Command::new("gsettings")
        .args(["set", schema, key, value])
        .status()
    {
        tracing::debug!("theme_export: gsettings {schema} {key}: {e}");
    }
}

/// `"r,g,b"` decimal triplet — the format KConfig expects for colour keys.
fn triplet(c: Color) -> String {
    format!("{},{},{}", c.r, c.g, c.b)
}

/// Pick whichever of the theme's text/background colour reads better on `bg`,
/// for foregrounds painted on top of the accent (e.g. selection text).
fn readable_on(bg: Color, theme: &ThemeConfig) -> Color {
    let lum = 0.299 * bg.r as f32 + 0.587 * bg.g as f32 + 0.114 * bg.b as f32;
    if lum > 140.0 {
        theme.colors.background
    } else {
        theme.colors.text
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use meridian_config::ThemeConfig;

    fn light_theme() -> ThemeConfig {
        let mut t = ThemeConfig::default();
        // Default palette is dark; lift the background so appearance is light.
        t.colors.background = Color::rgb(0xf2, 0xf2, 0xf2);
        t.colors.surface = Color::rgb(0xff, 0xff, 0xff);
        t.colors.text = Color::rgb(0x1a, 0x1a, 0x1a);
        t
    }

    #[test]
    fn triplet_formats_decimal_rgb() {
        assert_eq!(triplet(Color::rgb(0x20, 0x25, 0x2b)), "32,37,43");
        assert_eq!(triplet(Color::rgb(0, 0, 0)), "0,0,0");
        assert_eq!(triplet(Color::rgb(255, 255, 255)), "255,255,255");
    }

    #[test]
    fn readable_on_picks_contrasting_role() {
        let dark = ThemeConfig::default();
        // On a light fill, prefer the dark background colour.
        let on_light = readable_on(Color::rgb(0xff, 0xff, 0xff), &dark);
        assert_eq!(on_light, dark.colors.background);
        // On a dark fill, prefer the light text colour.
        let on_dark = readable_on(Color::rgb(0x10, 0x10, 0x10), &dark);
        assert_eq!(on_dark, dark.colors.text);
    }

    #[test]
    fn kdeglobals_dark_has_scheme_groups_and_breeze() {
        let s = kdeglobals_contents(&ThemeConfig::default());
        assert!(s.contains("[Colors:Window]"));
        assert!(s.contains("[Colors:View]"));
        assert!(s.contains("[Colors:Selection]"));
        assert!(s.contains("ColorScheme=MeridianDark"));
        assert!(s.contains("widgetStyle=Breeze"));
        // Window background is the surface colour (0x20252b -> 32,37,43).
        assert!(s.contains("BackgroundNormal=32,37,43"));
        // No accidental hex slipped into a KConfig value.
        assert!(!s.contains('#') || s.lines().filter(|l| l.starts_with('#')).count() == 1);
    }

    #[test]
    fn kdeglobals_light_switches_scheme_name() {
        let s = kdeglobals_contents(&light_theme());
        assert!(s.contains("ColorScheme=MeridianLight"));
    }

    #[test]
    fn gtk_ini_dark_prefers_dark() {
        let s = gtk_settings_ini(&ThemeConfig::default());
        assert!(s.contains("gtk-application-prefer-dark-theme=1"));
        assert!(s.contains("gtk-theme-name=Adwaita-dark"));
        assert!(s.contains("gtk-icon-theme-name=Papirus-Dark"));
    }

    #[test]
    fn gtk_ini_light_disables_dark() {
        let s = gtk_settings_ini(&light_theme());
        assert!(s.contains("gtk-application-prefer-dark-theme=0"));
        assert!(s.contains("gtk-theme-name=Adwaita\n"));
    }
}
